//error.js
export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

//fetch-details.js
export const FETCH_DETAILS = "FETCH_DETAILS";
export const CLEAR_DETAILS = "CLEAR_DETAILS";

//fetch-episodes.js
export const FETCH_EPISODES = "FETCH_EPISODES";
export const SET_EPISODES_UPDATING = "SET_EPISODES_UPDATING";
export const CLEAR_EPISODES = "CLEAR_EPISODES";

//fetch-genre-data.js
export const FETCH_GENRE_DATA = "FETCH_GENRE_DATA";
export const FETCH_MORE_GENRE_DATA = "FETCH_MORE_GENRE_DATA";
export const SET_GENRE_DATA_UPDATING = "SET_GENRE_DATA_UPDATING";
export const CLEAR_GENRE_DATA = "CLEAR_GENRE_DATA";

//fetch-initial-data.js
export const SET_INITIAL_DATA = "SET_INITIAL_DATA";
export const SET_DATA_UPDATING = "SET_DATA_UPDATING";
export const CLEAR_INITIAL_DATA = "CLEAR_INITIAL_DATA";

//genres.js
export const SET_GENRES = "SET_GENRES";
export const CLEAR_GENRES = "CLEAR_GENRES";
export const SET_SELECTED_GENRE = "SET_SELECTED_GENRE";
export const CLEAR_SELECTED_GENRE = "CLEAR_SELECTED_GENRE";

//misc.js
export const SET_DETAILS_POSITION = "SET_DETAILS_POSITION";
export const SET_EXPANDED_POSITION = "SET_EXPANDED_POSITION";
export const CLEAR_EXPANDED_POSITION = "CLEAR_EXPANDED_POSITION";
export const SET_EXPANDED_TRANSFORM_ORIGIN = "SET_EXPANDED_TRANSFORM_ORIGIN";
export const SET_HEADER_VIDEO = "SET_HEADER_VIDEO";
export const SET_PRESSED_KEY = "SET_PRESSED_KEY";
export const SET_SCROLLBAR_WIDTH = "SET_SCROLLBAR_WIDTH";
export const SET_ACTIVE_EXPANDED = "SET_ACTIVE_EXPANDED";
export const CLEAR_ACTIVE_EXPANDED = "CLEAR_ACTIVE_EXPANDED";
export const CLEAR_MISC = "CLEAR_MISC";

//player.js
export const SET_PLAYER_TV = "SET_PLAYER_TV";
export const SET_PLAYER_FILM = "SET_PLAYER_FILM";
export const SET_PLAYER_VOLUME = "SET_PLAYER_VOLUME";
export const SET_PLAYER_SEASONS = "SET_PLAYER_SEASONS";
export const SET_PLAYER_STATE = "SET_PLAYER_STATE";
export const SET_PLAYER_META_LOADED = "SET_PLAYER_META_LOADED";
export const CLEAR_PLAYER = "CLEAR_PLAYER";

//toggles.js
export const SET_IS_DETAILS = "SET_IS_DETAILS";
export const SET_GLOBAL_MUTE = "SET_GLOBAL_MUTE";
export const CLEAR_TOGGLES = "CLEAR_TOGGLES";

//user.js
export const SET_USER_INFO = "SET_USER_INFO";
export const SET_USER = "SET_USER";
export const LIKE_VIDEO = "LIKE_VIDEO";
export const REMOVE_LIKED_VIDEO = "REMOVE_LIKED_VIDEO";
export const DISLIKE_VIDEO = "DISLIKE_VIDEO";
export const REMOVE_DISLIKED_VIDEO = "REMOVE_DISLIKED_VIDEO";
export const CLEAR_USER = "CLEAR_USER";
