export const FETCH_INITIAL_DATA = "FETCH_INITIAL_DATA";
export const FETCH_DETAILS = "FETCH_DETAILS";
export const CLEAR_DETAILS = "CLEAR_DETAILS";
export const FETCH_EPISODES = "FETCH_EPISODES";
export const CLEAR_EPISODES = "CLEAR_EPISODES";

export const SET_DETAILS = "SET_DETAILS";
export const SET_DETAILS_POSITION = "SET_DETAILS_POSITION";

export const SET_GLOBAL_MUTE = "SET_GLOBAL_MUTE";
export const SET_HEADER_VIDEO_CAN_PLAY = "SET_HEADER_VIDEO_CAN_PLAY";
export const SET_SECONDARY_VIDEO_IS_PLAYING = "SET_SECONDARY_VIDEO_IS_PLAYING";
